### ISSUE TITLE
Leak de conexão quando há erro na operação

### ISSUE THREAD

**Issue by Brunomachadob** [thrust-bitcodes/database#15]
As operações com o statement não estão dentro de um try-finally fechando a conexão.
Isso faz com que erros na operação não fechem a conexão e causem estouro do pool na aplicação.

**Comment by brunobrandaosbx** [comment]
Problema ajustado e liberado na release [v0.2.25](https://github.com/thrust-bitcodes/database/releases/tag/0.2.25)
