### ISSUE TITLE
Falha de SQL Injection.

### ISSUE THREAD

**Issue by leonardodelfino** [thrust-bitcodes/database#7]
Descobri uma falha no ThrustJS.

Os métodos INSERT e UPDATE do database estão montando os parâmetros com concatenação de string. Devido a este fato é possível realizar cláusulas que possibilitam a injeção de código nesses métodos.

O exemplo abaixo foi testado e explora esta falha:

```
 // DDL: CREATE TABLE tabela_teste (id int,descricao text);

  sqlInjection: function (params, req, res) {
    var database = require('database'),
      db = database.createDbInstance(getBitcodeConfig('database')());

    var descricao = "'); DROP TABLE tabela_teste; SELECT ('tabela_teste";
    var resp = db.insert("tabela_teste", {
      id: 1,
      descricao: descricao
    });

    res.json(resp);
  }
```

Outro problema que estamos enfrentando é que esse REGEX não possibilita a execução de consultas com \n. Por esse motivo, ao criarmos arquivos com consultas maiores, estou tento que tratar as consultas removendo os \n e \t antes de passá-las para serem executadas ao thustjs.

**Comment by cneryjr** [comment]
Foi aplicada uma solução paliativa nos métodos que apresentaram o problema.
Uma solução definitiva será desenvolvida mais à frente!
