### ISSUE TITLE
incompatibilidade com Mysql

### ISSUE THREAD

**Issue by LuizTibo** [thrust-bitcodes/database#8]
Os métodos UPDATE, INSERT E DELETE estão sendo gerados com aspas duplas nos nomes das colunas e tabelas. Com isso estamos tendo erro de sintaxe nas execuções dos scripts para MYSQL

**Comment by cneryjr** [comment]
Obrigado por contribuir. Este erro já havia sido reportado e um Pull request foi submetido para correção. No entanto o pull request apresentou erros e retornou para o responsável (Tarciso Magalhães). Até o momento o pull request com a correção definitiva ainda não foi re-submetido.
Sugiro entrar em contato a se colocar a disposição para ajudar na correção, isso com certeza acelerará a versão com funcionalidade ajustada/corrigida. Obrigado!

**Comment by LuizTibo** [comment]
Ainda não está sendo definido o dialeto correto para o Mysql no momento que é criado a instancia do banco, está sendo utilizado o dialeto padrão do postgres.

**Comment by LuizTibo** [comment]
Nery, testei o dialeto, está funcionando. 

Obrigado.
