### ISSUE TITLE
Database não aceita consultas que iniciem com: WITH, ou parêteses, ou que possuam \n

### ISSUE THREAD

**Issue by leonardodelfino** [thrust-bitcodes/database#9]
O bitcode está dando erro ao executar consultas do tipo:

```
WITH temp as (SELECT ... )
SELECT temp ...
```

ou consultas do tipo
```
(SELECT ...)
UNION ALL
(SELECT ...)
```
ou qualquer consulta que possua \n em seu corpo.

Pelo que verifiquei há uma validação para ver se as consultas começam sempre com SELECT, o que está nos forçando a fazer o exemplo abaixo para algumas consultas.

Solução atual para executar os comandos:
```
SELECT * FROM (
  CONSULTA
) temp
```

**Comment by cneryjr** [comment]
Correção foi liberada na versão v0.2.17.
Obrigado!
